### ISSUE TITLE
Error when checking options srcset

### ISSUE THREAD

**Issue by trk** [chriswthomson/PageimageSrcset#7]
https://github.com/chriswthomson/PageimageSrcset/blob/ec872f436819cc2611ca6d22671213d84a303ad5/PageimageSrcset.module#L482

Possible fix

```php
if(!isset($options["srcset"]) || (isset($options["srcset"]) && $options["srcset"] !== false)) {
```

**Comment by jlahijani** [comment]
I can confirm this as well.

**Comment by chriswthomson** [comment]
Hi, @trk, @jlahijani.

Apologies - I've only just seen this now. Thanks for the suggested fix, have tweaked it slightly and added to the code.

Cheers,

Chris
